### PR TITLE
Fix for #233: TryGetObject threws.

### LINKED ISSUE #233: HoconValue.TryGetObject can throw System.ArgumentNullException
Looks like the issue is that `Hocon.Config.Root.TryGetObject` threw an exception:

https://github.com/akkadotnet/HOCON/blob/9d176be55aa9ef3a20df5db09e94a4c9c22fe99f/src/Hocon/Impl/HoconValue.cs#L69-L91

```
System.ArgumentNullException: 'Value cannot be null. Parameter name: source'
```

_Originally posted by @Aaronontheweb in https://github.com/akkadotnet/akka.net/issues/4234#issuecomment-589402354_

### PR DESCRIPTION
**Pull request by Arkatufus**
Closes #233
Bug was caused by multiple threads accessing the `Config.Root` property and `Config.Root` was not thread-safe.

### CODE REVIEW

File: src/Hocon.Configuration/Config.cs [hunk 1]
```diff
@@ -42,6 +42,7 @@ protected Config()
         protected Config(HoconValue value)
         {
             Value = (HoconValue)value.Clone(null);
+            Root = (HoconValue)value.Clone(null);
```
Comment (Aaronontheweb) [inline src/Hocon.Configuration/Config.cs]: Does `Root == Value` ?

File: src/Hocon.Configuration/Config.cs [hunk 2]
```diff
@@ -90,25 +93,7 @@ public Config(HoconRoot root, Config fallback) : this(root)
         /// </summary>
         public virtual bool IsEmpty => Value == EmptyValue && _fallbacks.Count == 0;
 
-        protected HoconValue _mergedValueCache = null;
-        public HoconValue Root
```
Comment (Aaronontheweb) [inline src/Hocon.Configuration/Config.cs]: LGTM

File: src/Hocon.Configuration/Config.cs [hunk 3]
```diff
@@ -196,15 +181,7 @@ public virtual Config WithFallback(Config fallback)
...
-            var result = new Config(Value);
-            foreach(var value in _fallbacks)
-            {
-                result._fallbacks.Add((HoconValue)value.Clone(null));
-            }
-            result.MergeConfig(fallback);
-
-            _mergedValueCache = null;
-            return result;
+            return new Config(this, fallback);
```
Comment (Aaronontheweb) [inline src/Hocon.Configuration/Config.cs]: Good idea

File: src/Hocon.Configuration/Config.cs (hunk 1 above)
Comment (Arkatufus) [reply src/Hocon.Configuration/Config.cs]: No, they're different instances, the original value is cloned twice, one to the `Value` property, the second is into the `Root` property.

Comment (Arkatufus) [reply src/Hocon.Configuration/Config.cs]: but at this point of the code, they are `Equal`, but not `ReferenceEqual`
