### PR TITLE
Fixed merge for substitutions

### LINKED ISSUE #127: Array is not being substituted correctly
Parsing this using akkadotnet
```
    c: {
        q: {
            𝗮: [𝟮, 𝟱]
        }
    }
    c: {
        m: ${c.q} {a: [6]}
    }
```
Results in:
(c.q.a should has changed)
```
    {
        c : {
            q : {
                𝗮 : [𝟲]
            },
            m : {
                a : [6]
            }
        }
    }
```

EXPECTED:
c.q.a should be unchanged

```
    {
        c : {
            q : {
                𝗮 : [𝟮, 𝟱]
            },
            m : {
                a : [6]
            }
        }
    }
```

### PR DESCRIPTION
**Pull request by IgorFedchenko**
Close #127 

The basic idea of the fix is that in current implementation substitution takes value "by reference" - which means that when object merge occurs the initial value, referenced in substitution, is modified. This could lead to lots of issues, not only with the once described in closing issue.

So the fix is basically make substitution to just deeply copy referenced sub-tree, so that it was safe to modify.

In the edge case when we do not need to modify referenced object we could still keep the "be reference" behavior instead of "by value". Not sure if it will save much performance and if it is important at all. But checking if we are somehow, somewhere modifying substituted value (not to say that we could reference one sub-tree, that includes another substitution that could also be modified then) - too complicated. So let's just take it by value and sleep soundly at night.

### CODE REVIEW

**Comment by IgorFedchenko** [comment]
Oops, seems like there are some failing tests... I will fix that

File: src/Hocon/Impl/HoconObject.cs [hunk 1]
```diff
@@ -394,7 +395,7 @@ public IHoconElement Clone(IHoconElement newParent)
             var clone = new HoconObject(newParent);
             foreach (var kvp in this)
             {
-                clone.SetField(kvp.Key, kvp.Value);
+                clone.SetField(kvp.Key, kvp.Value.CloneValue(clone) as HoconField);
```
Comment (IgorFedchenko) [inline src/Hocon/Impl/HoconObject.cs]: We need to clone all child elements as well, to make deep copy of referenced subtree

File: src/Hocon/Parser.cs [hunk 2]
```diff
@@ -184,7 +184,7 @@ private HoconValue ResolveSubstitution(HoconSubstitution sub)
 
             // third case, regular substitution
             _root.GetObject().TryGetValue(sub.Path, out var field);
-            return field;
+            return field?.Clone(field.Parent) as HoconValue;
```
Comment (IgorFedchenko) [inline src/Hocon/Parser.cs]: Returning clone of the references sub-tree, which is safe for modifications
