### PR TITLE
Do not mutate config.Fallback values when building Root property

### LINKED ISSUE #193: [CRITICAL] Fallbacks are mutable during traversal
Version: v1.3.1

Reproduction: https://github.com/akkadotnet/HOCON/pull/192

```csharp
[Fact]
        public void Should_dump_HOCON_with_2_Fallback()
        {
            var myHocon1 = ConfigurationFactory.ParseString(@"akka{
                actor.provider = cluster
                deployment{
                    /foo {
                        dispatcher = bar
                    }
                }
            }");

            var myHocon2 = ConfigurationFactory.ParseString(@"akka{
                debug{
                    received  = on
                }
                actor.provider = cluster
                deployment{
                    /foo {
                        dispatcher = foo
                    }
                    /bar {
                        mailbox = ""myFoo""
                    }
                }
            }");

            var myHocon3 = ConfigurationFactory.ParseString(@"akka{
                remote{
                    transport = ""foo""
                }
            }");

            var fullHocon = myHocon1
                .SafeWithFallback(myHocon2)
                .SafeWithFallback(myHocon3);

            // bug reproduction
            //fullHocon.GetString("akka.remote.transport").Should().Be("foo");

            var dump = fullHocon.DumpConfig();
            dump.Should().Contain(myHocon1.PrettyPrint(2));
            dump.Should().Contain(myHocon2.PrettyPrint(2));
            dump.Should().Contain(myHocon3.PrettyPrint(2));
        }
    }
```

If I run this test, as-is, all of the text for each fallback will be correctly preserved and the test will pass and produce the following output:

```
HOCON0
{
  akka : {
    actor : {
      provider : cluster
    },
    deployment : {
      /foo : {
        dispatcher : bar
      }
    }
  }
}

------------
HOCON1
{
  akka : {
    debug : {
      received : on
    },
    actor : {
      provider : cluster
    },
    deployment : {
      /foo : {
        dispatcher : foo
      },
      /bar : {
        mailbox : "myFoo"
      }
    }
  }
}

------------
HOCON2
{
  akka : {
    remote : {
      transport : "foo"
    }
  }
}
```

This is the expected output.

However, if I uncomment the `fullHocon.GetString("akka.remote.transport").Should().Be("foo")` line... Here is what we end up with instead:

```
HOCON0
{
  akka : {
    actor : {
      provider : cluster
    },
    deployment : {
      /foo : {
        dispatcher : bar
      }
    }
  }
}

------------
HOCON1
{
  akka : {
    debug : {
      received : on
    },
    actor : {
      provider : cluster
    },
    deployment : {
      /foo : {
        dispatcher : bar
      },
      /bar : {
        mailbox : "myFoo"
      }
    }
  }
}

------------
HOCON2
{
  akka : {
    remote : {
      transport : "foo"
    },
    debug : {
      received : on
    },
    actor : {
      provider : cluster
    },
    deployment : {
      /foo : {
        dispatcher : bar
      },
      /bar : {
        mailbox : "myFoo"
      }
    }
  }
}
```

The test fails in this scenario because the fallback HOCON values are populated with the values from the head.

In other words, with the following HOCON chain:

```
hocon1 --> fallback1 --> fallback2
```

When I call `hocon1.ToString("keyInFallback2")` all of the values from hocon1 will be mapped onto fallback1 and all of the values from fallback1 will be mapped onto fallback2. As a result, we can have race conditions and all sorts of other weird errors in the Akka.NET test suite.

This aligns with exactly the bugs I'm trying to track down in https://github.com/akkadotnet/akka.net/pull/4128

### PR DESCRIPTION
**Pull request by IgorFedchenko**
Close #193

### CODE REVIEW

File: src/Hocon.Configuration/Config.cs [hunk 1]
```diff
@@ -64,7 +64,7 @@ public virtual HoconValue Root
             get
             {
                 var elements = new List<IHoconElement>();
-                for (var config = this; config != null; config = config.Fallback)
+                for (var config = this; config != null; config = config.Fallback?.Copy())
```
Comment (Aaronontheweb) [inline src/Hocon.Configuration/Config.cs]: Wow... that was an easy fix.
