### PR TITLE
Fix config.Root calculation

### LINKED ISSUE #195: Lookups on configs with fallback are performing merge and allocations each time
We have a `Root` property in config, which is evaluated each time it is accessed, and getter is performing merging of all fallbacks into single config to use for lookup.

This `Root` is used in all lookups, so each lookup is performing lots of merging and allocations when there are lots of fallback values with lots of keys.

Since configs are immutable by design, should evalutate `Root` only once after fallback is added. So there will be only one allocation on new config creation, and lookups will be cheap.

### PR DESCRIPTION
**Pull request by IgorFedchenko**
Close #195

@Aaronontheweb This is based on #197 , so may be better to review/merge that one first.

The main improvement here is not only the fact that `Root` is not calculated on config creation - also `Config` instance now is not modified due to any private methods after is created with constructor.

Before there were some private setters, that were making harder to with `Config` as with immutable data structure. Now it is refactored to be fully built on constructor invocation, and we are safe to write code in this class without breaking immutability (of cause if we will not touch property setters).

### CODE REVIEW

**Comment by IgorFedchenko** [comment]
Ideally we should have all HOCON inner structures immutable, because all of this bugs are coming because entities reference each other and can modify each other, making it quite messy to debug. 

That nice moment, when the value is changed because of you just viewed it in your debugger...

But this is much more major task then fixing `Config` class.

**Comment by IgorFedchenko** [comment]
Since #198 turned out to be a mistake, rolled back it's changes. Now should be just fine.

File: src/Hocon.Configuration/Config.cs [hunk 1]
```diff
@@ -144,14 +137,10 @@ public virtual Config WithFallback(Config fallback)
...
-
-            var current = clone;
-            while (current.Fallback != null) current = current.Fallback;
-            current.Fallback = fallback.Copy();
-
-            return clone;
+            
+            // If Fallback is not set - we will set it in new copy
+            // If Fallback was set - just use it, but with adding new fallback values
+            return new Config((HoconValue) Value.Clone(null), Fallback?.WithFallback(fallback) ?? fallback);
```
Comment (IgorFedchenko) [inline src/Hocon.Configuration/Config.cs]: Turned out to be much more elegant solution for getting new config with fallback, and without internal state mutations.

File: src/Hocon.Configuration/Config.cs [hunk 2]
```diff
@@ -54,27 +66,12 @@ public Config(HoconRoot root) : base(root?.Value, root?.Substitutions ?? Enumera
...
-                    elements.AddRange(config.Value);
-                }
-
-                var aggregated = new HoconValue(null);
-                aggregated.AddRange(elements.AsEnumerable().Reverse());
-
-                return aggregated;
-            }
-        }
+        public virtual HoconValue Root { get; }
```
Comment (IgorFedchenko) [inline src/Hocon.Configuration/Config.cs]: So this is where we will safe on allocations. `Root` is immutable and calculated only once, in constructor

File: src/Hocon.Configuration/Config.cs [hunk 3]
```diff
@@ -54,27 +66,12 @@ public Config(HoconRoot root) : base(root?.Value, root?.Substitutions ?? Enumera
         /// <summary>
         ///     The configuration used as a secondary source.
         /// </summary>
-        public Config Fallback { get; private set; }
+        public Config Fallback { get; }
```
Comment (IgorFedchenko) [inline src/Hocon.Configuration/Config.cs]: Fallback should never change. It is either set, or not set for given config.

Comment (Aaronontheweb) [reply src/Hocon.Configuration/Config.cs]: Great idea.

File: src/Hocon.Configuration/Config.cs (hunk 2 above)
Comment (Aaronontheweb) [reply src/Hocon.Configuration/Config.cs]: :+1:

File: src/Hocon.Configuration/Config.cs [hunk 4]
```diff
@@ -199,6 +188,24 @@ public virtual Config WithFallback(Config fallback)
                 used.Add(kvp.Key);
             }
         }
+        
+        /// <summary>
+        /// Performs aggregation of Value and all Fallbacks into single <see cref="HoconValue"/> object
+        /// </summary>
+        private HoconValue GetRootValue()
```
Comment (Aaronontheweb) [inline src/Hocon.Configuration/Config.cs]: I'm much happier with this now that it's only run once.
