### PR TITLE
Fix parsing of quoted keys

### LINKED ISSUE #125: Parsing fails for quoted elements
When I use the following hocon
```
A.B = 1
A {
 "X.Y" = 1
}
```

Using via .net core 3.0 app fails as below

```
KeyNotFoundException: Could not find field with key `X` at path `X`
Hocon.HoconObject.GetField(HoconPath path)

KeyNotFoundException: Could not find field with key `X` at path `X`
Hocon.HoconObject.GetField(HoconPath path)
Hocon.HoconObject.GetField(string key)
Hocon.HoconObject.Merge(HoconObject other)
Hocon.HoconMergedObject..ctor(IHoconElement parent, List<HoconObject> objects)
Hocon.HoconValue.GetObject()
Hocon.Extensions.Configuration.HoconConfigurationFileParser.VisitObject(HoconValue value)
Hocon.Extensions.Configuration.HoconConfigurationFileParser.VisitHoconObject(HoconObject hObject)
Hocon.Extensions.Configuration.HoconConfigurationFileParser.Parse(Stream input)
Hocon.Extensions.Configuration.HoconConfigurationProvider.Load(Stream stream)
Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(bool reload)
Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(bool reload)
Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList<IConfigurationProvider> providers)
Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
Microsoft.Extensions.Hosting.HostBuilder.Build()
WebApplication68.Program.Main(string[] args) in Program.cs
+
            CreateHostBuilder(args).Build().Run();
```

Source code for my app is 
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Hocon.Extensions.Configuration;

namespace WebApplication68
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
             .ConfigureAppConfiguration((hostContext, configApp) =>
             {
                 var env = hostContext.HostingEnvironment;

                 configApp
                     .SetBasePath(env.ContentRootPath)
                     .AddHoconFile("akka.hocon",false)
                     .AddEnvironmentVariables(env.ApplicationName + "_")
                     .AddCommandLine(args);
             })

                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
}
```

### PR DESCRIPTION
**Pull request by IgorFedchenko**
Close #125 

So, here is the issue: during parsing of hocon object, we need to store object's keys. And with double-quoted keys, if we will include `'"'` sign in the key, we will not be able to make requests like `config.GetInt("a")` if `a` was double-quoted. Or, if we will omit `'"'` sign when storing the key ) which looks better, and this is what we are doing) - we will loose information that this key was double-quoted.

This information is not that important - until we will try to get value from object by it's path. That is exactly what happens when we call `config.GetObject("A")` for example - recursively it will iterate children, using keys of the object like hocon paths.

And guess what - for double-quoted key "X.Y" we have hocon path "X.Y" (we do not know that is was double-quoted, so it is handled like `X -> Y`), but object has `X.Y` key, and does not have `X`. So that's why we are getting error.

After some experiments with keeping double-quotes in keys and other stuff, I ended up with idea that it is better to think about such keys lookup as a special case - and each time when we are requesting child by hocon path, I am just checking if full path is preset in object's keys. So for path `X.Y` it will check `X.Y`, and then `X` -> `Y`.

### CODE REVIEW

**Comment by IgorFedchenko** [comment]
I have also reproduced this issue with sample in referenced issue, and ended up with the bug in core library.

File: src/Hocon/Impl/HoconObject.cs [hunk 1]
```diff
@@ -171,9 +171,15 @@ public HoconField GetField(HoconPath path)
...
             if (path.Count == 0)
                 throw new ArgumentException("Path is empty.", nameof(path));
-
-            var pathIndex = 0;
+            
             var currentObject = this;
+            
+            // Sometimes path may be a double-quoted string like "a.b.c" with quotes ommited,
+            // so check if there is such key first
+            if (currentObject.TryGetValue(path.ToString(), out var rootField))
```
Comment (Aaronontheweb) [inline src/Hocon/Impl/HoconObject.cs]: LGTM
